// API Endpoints
export const API_FAQ = process.env.REACT_APP_BASE_API_URL + "/faq";
export const API_AUTH_FAQ = process.env.REACT_APP_BASE_API_URL + "/api/faq";
export const API_NEWS = process.env.REACT_APP_BASE_API_URL + "/news";
export const API_AUTH_NEWS = process.env.REACT_APP_BASE_API_URL + "/api/news";
export const API_ORGANIZATION =
  process.env.REACT_APP_BASE_API_URL + "/organization";
export const API_AUTH_ORGANIZATION =
  process.env.REACT_APP_BASE_API_URL + "/api/organization";

// Action consts
export const SET_AUTH = "SET_AUTH";
export const AUTH_FAILED = "AUTH_FAILED";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS";
export const GET_FAQ_FAIL = "GET_FAQ_FAIL";
export const POST_FAQ_SUCCESS = "POST_FAQ_SUCCESS";
export const POST_FAQ_FAIL = "POST_FAQ_FAIL";
export const UPDATE_FAQ_SUCCESS = "UPDATE_FAQ_SUCCESS";
export const UPDATE_FAQ_FAIL = "UPDATE_FAQ_FAIL";
export const DELETE_FAQ_SUCCESS = "DELETE_FAQ_SUCCESS";
export const DELETE_FAQ_FAIL = "DELETE_FAQ_FAIL";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAIL = "GET_NEWS_FAIL";
export const GET_NEWS_DETAILS_SUCCESS = "GET_NEWS_DETAILS_SUCCESS";
export const GET_NEWS_DETAILS_FAIL = "GET_NEWS_DETAILS_FAIL";
export const POST_NEWS_SUCCESS = "POST_NEWS_SUCCESS";
export const POST_NEWS_FAIL = "POST_NEWS_FAIL";
export const UPDATE_NEWS_SUCCESS = "UPDATE_NEWS_SUCCESS";
export const UPDATE_NEWS_FAIL = "UPDATE_NEWS_FAIL";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAIL = "DELETE_NEWS_FAIL";
export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const GET_ORGANIZATIONS_FAIL = "GET_ORGANIZATIONS_FAIL";
export const CREATE_ORGANIZATIONS_SUCCESS = "CREATE_ORGANIZATIONS_SUCCESS";
export const CREATE_ORGANIZATIONS_FAIL = "CREATE_ORGANIZATIONS_FAIL";
export const UPDATE_ORGANIZATIONS_SUCCESS = "UPDATE_ORGANIZATIONS_SUCCESS";
export const UPDATE_ORGANIZATIONS_FAIL = "UPDATE_ORGANIZATIONS_FAIL";
export const DELETE_ORGANIZATIONS_SUCCESS = "DELETE_ORGANIZATIONS_SUCCESS";
export const DELETE_ORGANIZATIONS_FAIL = "DELETE_ORGANIZATIONS_FAIL";
export const GET_DONORSCOMMENT_FAIL = "GET_DONORSCOMMENT_FAIL";
export const GET_DONORSCOMMENT_SUCCESS = "GET_DONORSCOMMENT_SUCCESS";
export const POST_DONORSCOMMENT_FAIL = "POST_DONORSCOMMENT_FAIL";
export const POST_DONORSCOMMENT_SUCCESS = "POST_DONORSCOMMENT_SUCCESS";
